### ISSUE TITLE
English translation of help file...

### ISSUE THREAD

**Issue by rjgitdev** [quartexNOR/RaptorInvoice#2]
I don't know git hub yet but I google translated the help file... 
this is private repository at the moment - made invite for quartexNOR to collaborate:
https://github.com/rjgitdev/testing
[EnglishTranslationOfHTMLHelpFile.docx](https://github.com/quartexNOR/RaptorInvoice/files/3546357/EnglishTranslationOfHTMLHelpFile.docx)
[EnglishTranslationOfHTMLHelpFile.txt](https://github.com/quartexNOR/RaptorInvoice/files/3546358/EnglishTranslationOfHTMLHelpFile.txt)

**Comment by quartexNOR** [comment]
Hey!
Flattered that you did so. But the project itself is commonly known as abandonware.
This was a commercial product back in the day, but sales sadly didnt justify the cost of further development. But feel free to resurrect the project and bring it back to life.
Perhaps good to fork the code and add your translation there.
